(function(){
'use strict';
if(window.__PORTUGUES_M6_V1__)return;
window.__PORTUGUES_M6_V1__=true;
var TAB_KEY='central-v6:pt:active-module';
var oldRender=window.renderPortugueseMaster;
if(typeof oldRender!=='function')return;
function style(){if(document.getElementById('pt-m6-v1-style'))return;var e=document.createElement('style');e.id='pt-m6-v1-style';e.textContent='.ptm6-shell{margin-top:14px;background:transparent}.ptm6-frame-wrap{overflow:visible;border:0;background:transparent}.ptm6-frame{width:100%;min-height:2600px;border:0;display:block;background:transparent}@media(max-width:720px){.ptm6-shell{margin-top:10px}.ptm6-frame{min-height:3400px}}';document.head.appendChild(e)}
function resize(frame){try{var doc=frame.contentDocument||frame.contentWindow.document;if(!doc)return;function fit(){try{frame.style.height=Math.max(2200,doc.documentElement.scrollHeight,doc.body?doc.body.scrollHeight:0)+'px'}catch(_){}}fit();setTimeout(fit,80);setTimeout(fit,350);setTimeout(fit,900);if(frame.contentWindow&&frame.contentWindow.MutationObserver){var obs=new frame.contentWindow.MutationObserver(fit);obs.observe(doc.body,{subtree:true,childList:true,attributes:true})}}catch(e){console.warn('[PT M6/M7 resize]',e)}}
function baseTabs(active){return '<div class="ptm2-tabs"><button class="ptm2-tab'+(active==='m1'?' active':'')+'" onclick="PtM6V1.switchTab(\'m1\')">M1 · Ortografia</button><button class="ptm2-tab'+(active==='m2'?' active':'')+'" onclick="PtM6V1.switchTab(\'m2\')">M2 · Classes Nominais</button><button class="ptm2-tab'+(active==='m3'?' active':'')+'" onclick="PtM6V1.switchTab(\'m3\')">M3 · Conectivos</button><button class="ptm2-tab'+(active==='m4'?' active':'')+'" onclick="PtM6V1.switchTab(\'m4\')">M4 · Pronomes</button><button class="ptm2-tab'+(active==='m5'?' active':'')+'" onclick="PtM6V1.switchTab(\'m5\')">M5 · Colocação Pronominal</button><button class="ptm2-tab'+(active==='m6'?' active':'')+'" onclick="PtM6V1.switchTab(\'m6\')">M6 · Verbos</button><button class="ptm2-tab'+(active==='m7'?' active':'')+'" onclick="PtM6V1.switchTab(\'m7\')">M7 · Correlação e Vozes</button><button class="ptm2-tab'+(active==='m8'?' active':'')+'" onclick="PtM6V1.switchTab(\'m8\')">M8 · Sintaxe da Oração</button></div>'}
function tabs(){style();var active=localStorage.getItem(TAB_KEY)||'m1';if(active==='m6'){return baseTabs('m6')+'<div class="ptm6-shell"><div class="ptm6-frame-wrap"><iframe id="ptm6-native-frame" class="ptm6-frame" src="portugues-m6-v1.html" title="Português M6 — Verbos" onload="PtM6V1.resize(this)"></iframe></div></div>'}if(active==='m7'){return baseTabs('m7')+'<div class="ptm6-shell"><div class="ptm6-frame-wrap"><iframe id="ptm7-native-frame" class="ptm6-frame" src="portugues-m7-v1.html" title="Português M7 — Correlação Verbal e Vozes Verbais" onload="PtM6V1.resize(this)"></iframe></div></div>'}if(active==='m8'){return baseTabs('m8')+'<div class="ptm6-shell"><div class="ptm6-frame-wrap"><iframe id="ptm8-native-frame" class="ptm6-frame" src="portugues-m8-v1.html" title="Português M8 — Sintaxe da Oração" onload="PtM6V1.resize(this)"></iframe></div></div>'}var html=oldRender.apply(this,arguments);if(typeof html!=='string')return html;if(html.indexOf("PtM6V1.switchTab('m6')")<0)html=html.replace('</div>','<button class="ptm2-tab" onclick="PtM6V1.switchTab(\'m6\')">M6 · Verbos</button></div>');if(html.indexOf("PtM6V1.switchTab('m7')")<0)html=html.replace('</div>','<button class="ptm2-tab" onclick="PtM6V1.switchTab(\'m7\')">M7 · Correlação e Vozes</button></div>');if(html.indexOf("PtM6V1.switchTab('m8')")<0)html=html.replace('</div>','<button class="ptm2-tab" onclick="PtM6V1.switchTab(\'m8\')">M8 · Sintaxe da Oração</button></div>');return html}
window.PtM6V1={switchTab:function(v){localStorage.setItem(TAB_KEY,v);try{if(typeof window.renderAll==='function')window.renderAll();else if(typeof window.renderSubjects==='function')window.renderSubjects()}catch(e){console.warn('[PT M6/M7]',e)}},resize:resize};
window.renderPortugueseMaster=function(){return tabs.apply(this,arguments)};
try{if(typeof window.renderAll==='function')window.renderAll();else if(typeof window.renderSubjects==='function')window.renderSubjects()}catch(e){console.warn('[PT M6/M7]',e)}
})();
