(function(){
'use strict';
if(window.__PORTUGUES_M6_V1__)return;window.__PORTUGUES_M6_V1__=true;
var TAB_KEY='central-v6:pt:active-module',oldRender=window.renderPortugueseMaster;if(typeof oldRender!=='function')return;
function style(){if(document.getElementById('pt-m6-v1-style'))return;var e=document.createElement('style');e.id='pt-m6-v1-style';e.textContent='.ptm6-shell{margin-top:14px}.ptm6-frame{width:100%;min-height:2600px;border:0;display:block;background:transparent}@media(max-width:720px){.ptm6-frame{min-height:3400px}}';document.head.appendChild(e)}
function resize(frame){try{var doc=frame.contentDocument||frame.contentWindow.document;if(!doc)return;function fit(){try{frame.style.height=Math.max(2200,doc.documentElement.scrollHeight,doc.body?doc.body.scrollHeight:0)+'px'}catch(_){}}fit();setTimeout(fit,80);setTimeout(fit,350);setTimeout(fit,900);if(frame.contentWindow&&frame.contentWindow.MutationObserver){var obs=new frame.contentWindow.MutationObserver(fit);obs.observe(doc.body,{subtree:true,childList:true,attributes:true})}}catch(e){console.warn('[PT M6+ resize]',e)}}
var names={m1:'Ortografia',m2:'Classes Nominais',m3:'Conectivos',m4:'Pronomes',m5:'Colocação Pronominal',m6:'Verbos',m7:'Correlação e Vozes',m8:'Sintaxe da Oração',m9:'Sintaxe do Período',m10:'Pontuação',m11:'Concordância',m12:'Regência Verbal e Nominal',m13:'Crase',m14:'Coesão e Coerência',m15:'Semântica Geral',m16:'Interpretação de Textos'};
function baseTabs(active){var h='<div class="ptm2-tabs">';Object.keys(names).forEach(function(k){h+='<button class="ptm2-tab'+(active===k?' active':'')+'" onclick="PtM6V1.switchTab(\''+k+'\')">'+k.toUpperCase()+' · '+names[k]+'</button>'});return h+'</div>'}
function nativeFrame(active,src,title,id){return baseTabs(active)+'<div class="ptm6-shell"><iframe id="'+id+'" class="ptm6-frame" src="'+src+'" title="'+title+'" onload="PtM6V1.resize(this)"></iframe></div>'}
function tabs(){style();var active=localStorage.getItem(TAB_KEY)||'m1';if(/^m(?:6|7|8|9|10|11|12|13|14|15|16)$/.test(active)){var titles={m6:'Verbos',m7:'Correlação Verbal e Vozes Verbais',m8:'Sintaxe da Oração',m9:'Sintaxe do Período',m10:'Pontuação',m11:'Concordância',m12:'Regência Verbal e Nominal',m13:'Crase',m14:'Coesão e Coerência',m15:'Semântica Geral',m16:'Interpretação de Textos'};return nativeFrame(active,'portugues-'+active+'-v1.html','Português '+active.toUpperCase()+' — '+titles[active],'pt'+active+'-native-frame')}var html=oldRender.apply(this,arguments);if(typeof html!=='string')return html;['m6','m7','m8','m9','m10','m11','m12','m13','m14','m15','m16'].forEach(function(k){if(html.indexOf("PtM6V1.switchTab('"+k+"')")<0)html=html.replace('</div>','<button class="ptm2-tab" onclick="PtM6V1.switchTab(\''+k+'\')">'+k.toUpperCase()+' · '+names[k]+'</button></div>')});return html}
window.PtM6V1={switchTab:function(v){localStorage.setItem(TAB_KEY,v);try{if(typeof window.renderAll==='function')window.renderAll();else if(typeof window.renderSubjects==='function')window.renderSubjects()}catch(e){console.warn('[PT M6+]',e)}},resize:resize};window.renderPortugueseMaster=function(){return tabs.apply(this,arguments)};try{if(typeof window.renderAll==='function')window.renderAll();else if(typeof window.renderSubjects==='function')window.renderSubjects()}catch(e){console.warn('[PT M6+]',e)}
})();
