import { createServer } from 'node:http';
import { readFile, readdir, mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { extname, join, resolve, relative } from 'node:path';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import { chromium } from 'playwright';

const root=resolve('.'), evidence=join(root,'audits/base-completa-20261007');
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.pdf':'application/pdf','.ico':'image/x-icon'};
const empty='<html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div class="central-settings-body"></div></body></html>';
const apiUser={id:'A',name:'Test A',role:'aluno'};
const syncSource=await readFile(join(root,'sync-client.js'),'utf8');
const localStateSource=await readFile(join(root,'sync-local-state.js'),'utf8');
const server=createServer(async(req,res)=>{
  const url=new URL(req.url,'http://127.0.0.1');
  if(url.pathname==='/api/auth'){
    res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});
    res.end(JSON.stringify(url.searchParams.get('action')==='logout'?{ok:true}:{authenticated:true,user:apiUser}));return;
  }
  if(url.pathname.startsWith('/api/')){res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end('{}');return}
  if(url.pathname==='/__audit_harness__.html'){res.writeHead(200,{'Content-Type':'text/html'});res.end(empty);return}
  const file=resolve(root,'.'+(url.pathname==='/'?'/central-v119.html':decodeURIComponent(url.pathname)));
  if(file!==root&&!file.startsWith(root+'/')){res.writeHead(403);res.end();return}
  try{const body=await readFile(file);res.writeHead(200,{'Content-Type':mime[extname(file)]||'application/octet-stream'});res.end(body)}
  catch{res.writeHead(404);res.end('Not found')}
});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});
const resultPath=join(evidence,'browser-results.json');
const results=existsSync(resultPath)?JSON.parse(await readFile(resultPath,'utf8')):{date:new Date().toISOString(),baseSha:'b709b6f',isolation:null,themes:null,sweep:null};
const mode=process.argv[2]||'all';
async function mockApi(page,cloud,uid){
  await page.route('**/api/**',async route=>{
    const req=route.request(),u=new URL(req.url()),user={id:uid.current,name:'Test '+uid.current,role:'aluno'};
    let body={};
    if(u.pathname==='/api/auth')body={authenticated:true,user};
    else if(u.pathname==='/api/sync'){
      const id=uid.current,stored=cloud.get(id);
      if(req.method()==='GET')body=stored?{exists:true,revision:stored.revision,payload:stored.payload}:{exists:false};
      else {const input=req.postDataJSON();const revision=(stored?.revision||0)+1;cloud.set(id,{revision,payload:input.payload});body={revision}}
    }else if(u.pathname==='/api/backups')body={ok:true};
    await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});
  });
}
async function isolation(){
  const context=await browser.newContext({serviceWorkers:'block'}),cloud=new Map(),uid={current:'A'};
  async function open(id){uid.current=id;const p=await context.newPage();await mockApi(p,cloud,uid);await p.route('**/__audit_harness__.html',r=>r.fulfill({status:200,contentType:'text/html',body:empty}));await p.route('**/sync-client.js',r=>r.fulfill({status:200,contentType:'text/javascript',body:syncSource}));await p.route('**/sync-local-state.js*',r=>r.fulfill({status:200,contentType:'text/javascript',body:localStateSource}));await p.goto(base+'/__audit_harness__.html');await p.evaluate(id=>{window.BASE_COMPLETA_USER={id,name:'Test '+id};window.__BASE_COMPLETA_USER_ID__=id;if(id==='A'&&!localStorage.getItem('central-v6:local-owner'))localStorage.setItem('central-v6:audit-legacy','legacy-progress')},id);await p.addScriptTag({url:base+'/sync-client.js'});await p.waitForFunction(id=>localStorage.getItem('central-v6:local-owner')===id,id);return p}
  let p=await open('A');assert.equal(await p.evaluate(()=>localStorage.getItem('central-v6:audit-legacy')),'legacy-progress');await p.evaluate(()=>{localStorage.setItem('central-v6:audit-exclusive','A-only');localStorage.setItem('central-v6:pt:auto24:test','preserved')});await p.reload();await p.evaluate(()=>{window.BASE_COMPLETA_USER={id:'A'};window.__BASE_COMPLETA_USER_ID__='A'});await p.addScriptTag({url:base+'/sync-client.js'});await p.waitForFunction(()=>localStorage.getItem('central-v6:local-owner')==='A');assert.equal(await p.evaluate(()=>localStorage.getItem('central-v6:audit-exclusive')),'A-only');await p.close();
  p=await open('B');const bSeesA=await p.evaluate(()=>localStorage.getItem('central-v6:audit-exclusive'));assert.equal(bSeesA,null);await p.evaluate(()=>localStorage.setItem('central-v6:audit-exclusive','B-only'));await context.setOffline(true);await p.close();
  p=await open('A');const aRestored=await p.evaluate(()=>localStorage.getItem('central-v6:audit-exclusive'));assert.equal(aRestored,'A-only');assert.equal(await p.evaluate(()=>localStorage.getItem('central-v6:pt:auto24:test')),'preserved');await p.close();
  p=await open('B');const bRestored=await p.evaluate(()=>localStorage.getItem('central-v6:audit-exclusive'));assert.equal(bRestored,'B-only');await p.close();
  p=await open('A');assert.equal(await p.evaluate(()=>localStorage.getItem('central-v6:audit-exclusive')),'A-only');await p.close();
  await context.setOffline(false);p=await open('B');await p.evaluate(()=>window.dispatchEvent(new Event('online')));await p.waitForTimeout(1500);assert.equal(cloud.get('B')?.payload?.['central-v6:audit-exclusive'],'B-only');assert.equal(cloud.get('B')?.payload?.['central-v6:local-owner'],undefined);
  const out={bSeesA,aRestored,bRestored,pass:true,offline:true,reconnected:true,cloudB:cloud.get('B')?.payload?.['central-v6:audit-exclusive']};await p.close();await context.close();return out;
}
async function bootIsolation(){
 const context=await browser.newContext({serviceWorkers:'block'});
 async function home(id){const p=await context.newPage();await p.route('**/api/auth**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({authenticated:true,user:{id,name:'Test '+id,role:'aluno'}})}));await p.addInitScript(()=>{const write=Document.prototype.write;Document.prototype.write=function(...args){window.__auditOwnerAtDocumentWrite=localStorage.getItem('central-v6:local-owner');return write.apply(this,args)}});await p.goto(base+'/central-v119.html',{waitUntil:'domcontentloaded'});await p.waitForFunction(id=>localStorage.getItem('central-v6:local-owner')===id,id,{timeout:15000});return p}
 let p=await home('A');await p.evaluate(()=>localStorage.setItem('central-v6:audit-exclusive','A-only'));await p.close();
 p=await home('B');const result=await p.evaluate(()=>({ownerAtWrite:window.__auditOwnerAtDocumentWrite,bSeesA:localStorage.getItem('central-v6:audit-exclusive')}));assert.equal(result.ownerAtWrite,'B');assert.equal(result.bSeesA,null);await p.close();await context.close();return {...result,pass:true}
}
async function walk(dir){const out=[];for(const ent of await readdir(dir,{withFileTypes:true})){if(ent.name==='node_modules'||ent.name==='.git'||ent.name==='audits')continue;const path=join(dir,ent.name);if(ent.isDirectory())out.push(...await walk(path));else if(ent.name.endsWith('.html'))out.push(relative(root,path))}return out}
async function sweep(){
  const files=(await walk(root)).sort(),widths=[360,390,768,1024,1440],issues=[],pagesWithOverflow=new Set();let cases=0,main404=0,overflow=0,errors=0,asset404=0;
  const context=await browser.newContext({serviceWorkers:'block'});
  for(const file of files){for(const width of widths){const page=await context.newPage();await page.setViewportSize({width,height:850});const local=[];page.on('pageerror',e=>local.push({kind:'js',value:e.message}));page.on('response',r=>{if(r.status()===404&&new URL(r.url()).origin===base&&!r.url().includes('/api/'))local.push({kind:'404',value:r.url()})});let response;
    try{response=await page.goto(base+'/'+file,{waitUntil:'domcontentloaded',timeout:20000});await page.waitForTimeout(file==='central-v119.html'?1200:120);const dims=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,body:document.body?.scrollWidth||0}));if(dims.scroll>dims.width+1||dims.body>dims.width+1){overflow++;pagesWithOverflow.add(file);local.push({kind:'overflow',value:dims})}if(!response||response.status()===404)main404++;}
    catch(e){local.push({kind:'navigation',value:e.message});main404++}
    errors+=local.filter(x=>x.kind==='js'||x.kind==='navigation').length;asset404+=local.filter(x=>x.kind==='404').length;if(local.length)issues.push({file,width,issues:local.slice(0,8)});cases++;await page.close();
  }console.log('sweep progress',file,cases)}
  await context.close();return {pages:files.length,widths,cases,main404,overflow,asset404,errors,pagesWithOverflow:[...pagesWithOverflow],issues};
}
async function screenshots(){const context=await browser.newContext({serviceWorkers:'block'});const shots=[['modules/trabalho/base-completa/m04.html',390,'m04-mobile.png'],['modules/trabalho/base-completa/m08.html',390,'m08-mobile.png'],['modules/trabalho/base-completa/m17.html',390,'m17-mobile.png'],['tools/cronograma.html',390,'cronograma-mobile.png'],['central-v119.html',390,'home-390.png'],['central-v119.html',1440,'home-1440.png']];
 for(const [file,width,name] of shots){const p=await context.newPage();await p.setViewportSize({width,height:850});await p.goto(base+'/'+file,{waitUntil:'domcontentloaded'});await p.waitForTimeout(file==='central-v119.html'?1500:200);await p.screenshot({path:join(evidence,name),fullPage:false});await p.close()}
 for(const [theme,name] of [['dark-premium','dark-premium.png'],['oled-black','oled.png']]){const p=await context.newPage();await p.setViewportSize({width:390,height:850});await p.goto(base+'/central-v119.html',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.documentElement.dataset.centralReady==='true',null,{timeout:20000});await p.evaluate(t=>window.setCentralTheme(t),theme);await p.waitForTimeout(200);await p.screenshot({path:join(evidence,name),fullPage:false});await p.close()}
 await context.close();return shots.map(x=>x[2]).concat(['dark-premium.png','oled.png'])}
async function themes(){const context=await browser.newContext({serviceWorkers:'block'}),p=await context.newPage();await p.setViewportSize({width:390,height:850});const themes=['paper-yellow','paper-white','sage-study','editorial-gray','legal-mist','dark-premium','oled-black'];let checks=[];
 for(const theme of themes){await p.goto(base+'/__audit_harness__.html');await p.evaluate(t=>localStorage.setItem('central-v6:appearance',t),theme);await p.addScriptTag({url:base+'/ui/theme.js'});await p.addScriptTag({url:base+'/ui/appearance-themes-v1.js'});await p.waitForTimeout(60);const before=await p.evaluate(()=>({attr:document.documentElement.getAttribute('data-central-theme'),key:localStorage.getItem('central-v6:appearance')}));await p.reload();await p.addScriptTag({url:base+'/ui/theme.js'});await p.addScriptTag({url:base+'/ui/appearance-themes-v1.js'});const after=await p.evaluate(()=>({attr:document.documentElement.getAttribute('data-central-theme'),key:localStorage.getItem('central-v6:appearance'),overflow:document.documentElement.scrollWidth>innerWidth+1}));checks.push({theme,before,after});assert.equal(before.attr,theme);assert.equal(after.attr,theme);assert.equal(after.key,theme);assert.equal(after.overflow,false)}
 for(const [legacy,expected] of [['light','paper-white'],['dark','dark-premium'],['oled','oled-black']]){await p.goto(base+'/__audit_harness__.html');await p.evaluate(t=>localStorage.setItem('central-v6:appearance',t),legacy);await p.addScriptTag({url:base+'/ui/appearance-themes-v1.js'});await p.waitForTimeout(50);assert.equal(await p.evaluate(()=>document.documentElement.getAttribute('data-central-theme')),expected)}await p.close();await context.close();return {themes:checks.length,legacy:3,pass:true,checks}}
async function realThemes(){const context=await browser.newContext({serviceWorkers:'block'}),p=await context.newPage();await p.setViewportSize({width:390,height:850});await p.goto(base+'/central-v119.html',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.documentElement.dataset.centralReady==='true',null,{timeout:20000});const checks=[];for(const theme of ['paper-yellow','paper-white','sage-study','editorial-gray','legal-mist','dark-premium','oled-black']){await p.evaluate(t=>window.setCentralTheme(t),theme);await p.waitForTimeout(100);const before=await p.evaluate(()=>({attr:document.documentElement.getAttribute('data-central-theme'),key:localStorage.getItem('central-v6:appearance')}));await p.reload({waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.documentElement.dataset.centralReady==='true',null,{timeout:20000});const after=await p.evaluate(()=>({attr:document.documentElement.getAttribute('data-central-theme'),key:localStorage.getItem('central-v6:appearance'),overflow:document.documentElement.scrollWidth>innerWidth+1,bg:getComputedStyle(document.body).backgroundColor,bgVar:getComputedStyle(document.documentElement).getPropertyValue('--bg').trim(),rootClass:document.documentElement.className,cardBg:getComputedStyle(document.querySelector('#homeView .subject')||document.body).backgroundColor,continuePath:(()=>{let e=document.getElementById('continueBox');return [e,e?.parentElement,e?.parentElement?.parentElement].filter(Boolean).map(n=>({tag:n.tagName,id:n.id,cls:n.className,bg:getComputedStyle(n).backgroundColor,color:getComputedStyle(n).color}))})(),heading:getComputedStyle(document.querySelector('#disciplinasHome h2')||document.body).color,themeCss:[...document.styleSheets].some(x=>x.href?.includes('appearance-themes-v1.css'))}));await p.goto(base+'/tools/cronograma.html',{waitUntil:'domcontentloaded'});await p.goto(base+'/central-v119.html',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.documentElement.dataset.centralReady==='true',null,{timeout:20000});const navigated=await p.evaluate(()=>({attr:document.documentElement.getAttribute('data-central-theme'),key:localStorage.getItem('central-v6:appearance')}));checks.push({theme,before,after,navigated});assert.equal(after.attr,theme);assert.equal(after.key,theme);assert.equal(navigated.attr,theme);assert.equal(navigated.key,theme);if(theme==='dark-premium'){assert.notEqual(after.bg,'rgb(243, 249, 253)');assert.notEqual(after.cardBg,'rgb(255, 255, 255)')}if(theme==='oled-black'){assert.equal(after.bg,'rgb(0, 0, 0)');assert.notEqual(after.cardBg,'rgb(255, 255, 255)')}}await p.close();await context.close();return checks}
async function layouts(){const context=await browser.newContext({serviceWorkers:'block'}),files=['central-v119.html','tools/cronograma.html','modules/trabalho/base-completa/m04.html','modules/trabalho/base-completa/m08.html','modules/trabalho/base-completa/m17.html','usuarios.html'],views=[['mobile-portrait',390,844],['mobile-landscape',844,390],['tablet-portrait',768,1024],['tablet-landscape',1024,768],['zoom-200',1440,900]],checks=[];for(const file of files)for(const [name,width,height] of views){const p=await context.newPage();await p.setViewportSize({width,height});await p.goto(base+'/'+file,{waitUntil:'domcontentloaded'});if(file==='central-v119.html')await p.waitForFunction(()=>document.documentElement.dataset.centralReady==='true',null,{timeout:20000});if(name==='zoom-200')await p.evaluate(()=>document.documentElement.style.zoom='2');const result=await p.evaluate(()=>({viewport:innerWidth,scroll:document.documentElement.scrollWidth,body:document.body.scrollWidth,overflow:document.documentElement.scrollWidth>innerWidth+1}));checks.push({file,view:name,...result});await p.close()}await context.close();return {cases:checks.length,overflows:checks.filter(x=>x.overflow),checks}}
async function accessibility(){const context=await browser.newContext({serviceWorkers:'block'}),files=['central-v119.html','login.html','usuarios.html','tools/cronograma.html','modules/trabalho/base-completa/m04.html'],checks=[];for(const file of files){const p=await context.newPage();await p.route('**/api/auth**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(file==='login.html'?{authenticated:false}:{authenticated:true,user:{id:'admin-audit',name:'Admin Audit',role:'admin'}})}));await p.setViewportSize({width:390,height:850});await p.goto(base+'/'+file,{waitUntil:'domcontentloaded'});if(file==='central-v119.html')await p.waitForFunction(()=>document.documentElement.dataset.centralReady==='true',null,{timeout:20000});else await p.waitForTimeout(200);const result=await p.evaluate(()=>{const visible=e=>{const s=getComputedStyle(e);return s.display!=='none'&&s.visibility!=='hidden'&&!!e.getClientRects().length};const buttons=[...document.querySelectorAll('button,[role="button"]')].filter(visible).filter(e=>!((e.getAttribute('aria-label')||e.getAttribute('title')||e.textContent||'').trim()));const links=[...document.querySelectorAll('a[href]')].filter(visible).filter(e=>!((e.getAttribute('aria-label')||e.getAttribute('title')||e.textContent||e.querySelector('img')?.alt||'').trim()));const inputs=[...document.querySelectorAll('input:not([type="hidden"]),textarea,select')].filter(visible).filter(e=>!((e.getAttribute('aria-label')||e.getAttribute('title')||e.labels?.[0]?.textContent||'').trim()));return {unnamedButtons:buttons.length,emptyLinks:links.length,unlabeledInputs:inputs.length,h1:document.querySelectorAll('h1').length,dialogCount:document.querySelectorAll('[role="dialog"],dialog').length}});checks.push({file,...result});await p.close()}await context.close();return checks}
async function pwa(){
 const context=await browser.newContext(),p=await context.newPage();await p.goto(base+'/modules/trabalho/base-completa/m04.html');
 await p.evaluate(async()=>{await navigator.serviceWorker.register('/sw.js',{scope:'/'});await navigator.serviceWorker.ready});
 await p.waitForFunction(()=>!!navigator.serviceWorker.controller,{timeout:15000});await p.evaluate(()=>fetch('/api/auth?action=me'));await p.reload();
 await p.evaluate(()=>localStorage.setItem('central-v6:audit-offline-progress','done'));
 await context.setOffline(true);const response=await p.reload({waitUntil:'domcontentloaded',timeout:15000});
 const offline={status:response?.status(),progress:await p.evaluate(()=>localStorage.getItem('central-v6:audit-offline-progress'))};assert.equal(offline.status,200);assert.equal(offline.progress,'done');
 await context.setOffline(false);await p.evaluate(async()=>{const c=await caches.open('central-audit-stale');await c.put('/__audit_stale__',new Response('old'));await navigator.serviceWorker.register('/sw.js?audit=2',{scope:'/'});await navigator.serviceWorker.ready});
 await p.waitForFunction(()=>navigator.serviceWorker.controller?.scriptURL.includes('audit=2'),null,{timeout:15000});
 for(let i=0;i<50;i++){if(!(await p.evaluate(async()=>(await caches.keys()).includes('central-audit-stale'))))break;await p.waitForTimeout(100)}
 const updated=await p.evaluate(async()=>({progress:localStorage.getItem('central-v6:audit-offline-progress'),cacheKeys:await caches.keys()}));assert.equal(updated.progress,'done');assert.equal(updated.cacheKeys.includes('central-audit-stale'),false);await p.close();await context.close();return {offline,updated,pass:true}
}
async function editorSanitization(){
 const source=await readFile(join(root,'api/content-editor.js'),'utf8');const match=source.match(/function cleanHtml\(value\)\{[\s\S]*?\n\}/);assert(match);const cleanHtml=vm.runInNewContext('('+match[0]+')');
 const attacks=['<script>window.__auditFired=1</script>','<img src=x onerror=window.__auditFired=1>','<a href="javascript:window.__auditFired=1">x</a>','<a href=javascript:window.__auditFired=1>x</a>','<iframe srcdoc="<script>window.__auditFired=1</script>"></iframe>','<svg onload=window.__auditFired=1></svg>'];
 const context=await browser.newContext({serviceWorkers:'block'});const checks=[];
 for(const input of attacks){const serverHtml=cleanHtml(input),p=await context.newPage();await p.addInitScript(()=>{window.__auditFired=0});
 await p.route('**/__audit_harness__.html',r=>r.fulfill({status:200,contentType:'text/html',body:'<html><body><div class="bc-native-reader-overlay"><div class="bc-native-reader-title"><b>Audit</b></div><article class="bc-native-article"><p>Original</p></article><aside class="bc-native-reader-tools"></aside></div></body></html>'}));
 await p.route('**/api/auth**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({authenticated:true,user:{id:'A',role:'aluno'}})}));
 await p.route('**/api/content-editor**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({exists:true,html:serverHtml})}));
 await p.goto(base+'/__audit_harness__.html');await p.addScriptTag({url:base+'/ui/visual-editor-v1.js'});await p.waitForTimeout(150);
 const state=await p.evaluate(()=>({html:document.querySelector('.bc-native-article')?.innerHTML||'',fired:window.__auditFired,unsafe:!!document.querySelector('.bc-native-article script,.bc-native-article iframe,.bc-native-article [onerror],.bc-native-article [onload],.bc-native-article [href^="javascript:"]')}));assert.equal(state.fired,0);assert.equal(state.unsafe,false);checks.push({input,serverHtml,state});await p.close()}
 const formatting=cleanHtml('<h2>Título</h2><table><tr><td>Célula</td></tr></table><figure><img src="/assets/base-completa-symbol.webp"></figure>');assert(formatting.includes('<table>')&&formatting.includes('<figure>'));await context.close();return {cases:checks.length,pass:true,checks,formatting}
}
try{await mkdir(evidence,{recursive:true});if(mode==='all'||mode==='isolation')results.isolation=await isolation();if(mode==='all'||mode==='boot')results.bootIsolation=await bootIsolation();if(mode==='all'||mode==='themes')results.themes=await themes();if(mode==='all'||mode==='sweep')results.sweep=await sweep();if(mode==='all'||mode==='screenshots')results.screenshots=await screenshots();if(mode==='all'||mode==='real-themes')results.realThemes=await realThemes();if(mode==='all'||mode==='accessibility')results.accessibility=await accessibility();if(mode==='all'||mode==='layouts')results.layouts=await layouts();if(mode==='all'||mode==='pwa')results.pwa=await pwa();if(mode==='all'||mode==='sanitization')results.sanitization=await editorSanitization();results.date=new Date().toISOString();await writeFile(resultPath,JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify(results));}
finally{await browser.close();server.close()}
