import { createHash } from 'node:crypto';
import { neon } from '@neondatabase/serverless';

let schemaPromise;

function getSql() {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error('DATABASE_URL não configurada');
  return neon(url);
}
function userIdFor(syncKey) {
  const pepper = process.env.CENTRAL_SYNC_PEPPER;
  if (!pepper || pepper.length < 24) throw new Error('CENTRAL_SYNC_PEPPER não configurado ou muito curto');
  return createHash('sha256').update(`${pepper}:${syncKey}`).digest('hex');
}
function cleanString(value, max = 160) { return String(value ?? '').trim().slice(0, max); }
function cleanTimestamp(value) { const n=Number(value); return Number.isFinite(n)&&n>=0?Math.trunc(n):0; }
function cleanPct(value, nullable=false) { if(nullable&&(value==null||value===''))return null;const n=Number(value);if(!Number.isFinite(n))return nullable?null:0;return Math.max(0,Math.min(100,Math.round(n*10)/10)); }
function safeJson(value, fallback, max=500_000) { try{const text=JSON.stringify(value);if(text.length>max)return fallback;return JSON.parse(text)}catch{return fallback} }
function validDate(value){const s=cleanString(value,10);return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:''}
function validIso(value){const s=cleanString(value,40),n=Date.parse(s);return Number.isFinite(n)?new Date(n).toISOString():''}
function bool(v){return v===true||v===1||v==='1'||v==='true'}
async function runBatches(sql,queries,size=1000){if(!Array.isArray(queries)||!queries.length)return;for(let i=0;i<queries.length;i+=size)await sql.transaction(queries.slice(i,i+size))}

async function ensureSchema(sql){
 if(!schemaPromise){schemaPromise=(async()=>{
  await sql.transaction([
   sql`CREATE TABLE IF NOT EXISTS central_sync_users (id TEXT PRIMARY KEY, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
   sql`CREATE TABLE IF NOT EXISTS central_agenda_days (user_id TEXT NOT NULL REFERENCES central_sync_users(id) ON DELETE CASCADE, agenda_date DATE NOT NULL, items JSONB NOT NULL DEFAULT '[]'::jsonb, client_updated_at BIGINT NOT NULL DEFAULT 0, server_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (user_id, agenda_date))`,
   sql`CREATE TABLE IF NOT EXISTS central_topic_progress (user_id TEXT NOT NULL REFERENCES central_sync_users(id) ON DELETE CASCADE, topic_key TEXT NOT NULL, subject_id TEXT NOT NULL, topic_id TEXT, module_id TEXT, theory_pct NUMERIC(5,1) NOT NULL DEFAULT 0, law_pct NUMERIC(5,1), anki_pct NUMERIC(5,1) NOT NULL DEFAULT 0, questions_pct NUMERIC(5,1) NOT NULL DEFAULT 0, overall_pct NUMERIC(5,1) NOT NULL DEFAULT 0, components JSONB NOT NULL DEFAULT '{}'::jsonb, client_updated_at BIGINT NOT NULL DEFAULT 0, server_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (user_id, topic_key))`,
   sql`CREATE TABLE IF NOT EXISTS central_anki_cards (user_id TEXT NOT NULL REFERENCES central_sync_users(id) ON DELETE CASCADE, card_id TEXT NOT NULL, stats JSONB NOT NULL DEFAULT '{}'::jsonb, suspended BOOLEAN NOT NULL DEFAULT FALSE, overrides JSONB NOT NULL DEFAULT '{}'::jsonb, custom_card JSONB, deleted BOOLEAN NOT NULL DEFAULT FALSE, client_updated_at BIGINT NOT NULL DEFAULT 0, server_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (user_id, card_id))`,
   sql`CREATE TABLE IF NOT EXISTS central_anki_settings (user_id TEXT PRIMARY KEY REFERENCES central_sync_users(id) ON DELETE CASCADE, custom_decks JSONB NOT NULL DEFAULT '[]'::jsonb, swap_buttons BOOLEAN NOT NULL DEFAULT FALSE, client_updated_at BIGINT NOT NULL DEFAULT 0, server_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
   sql`CREATE TABLE IF NOT EXISTS central_decorando_items (user_id TEXT NOT NULL REFERENCES central_sync_users(id) ON DELETE CASCADE, item_id TEXT NOT NULL, importance TEXT, note TEXT, highlights JSONB NOT NULL DEFAULT '{}'::jsonb, answered BOOLEAN NOT NULL DEFAULT FALSE, deleted_at TEXT, client_updated_at BIGINT NOT NULL DEFAULT 0, server_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (user_id, item_id))`,
   sql`CREATE TABLE IF NOT EXISTS central_decorando_attempts (user_id TEXT NOT NULL REFERENCES central_sync_users(id) ON DELETE CASCADE, attempt_key TEXT NOT NULL, item_id TEXT NOT NULL, attempted_at TIMESTAMPTZ NOT NULL, choice BOOLEAN NOT NULL, correct BOOLEAN NOT NULL, server_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (user_id, attempt_key))`,
   sql`CREATE TABLE IF NOT EXISTS central_decorando_settings (user_id TEXT PRIMARY KEY REFERENCES central_sync_users(id) ON DELETE CASCADE, preferences JSONB NOT NULL DEFAULT '{}'::jsonb, client_updated_at BIGINT NOT NULL DEFAULT 0, server_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
   sql`CREATE TABLE IF NOT EXISTS central_question_sessions (user_id TEXT NOT NULL REFERENCES central_sync_users(id) ON DELETE CASCADE, session_id TEXT NOT NULL, subject_id TEXT, subject_name TEXT, topic_id TEXT, topic_uid TEXT, module_id TEXT, topic_name TEXT, session_date DATE, quantity INTEGER NOT NULL DEFAULT 0, correct INTEGER NOT NULL DEFAULT 0, minutes INTEGER, difficulty TEXT, comment TEXT, deleted BOOLEAN NOT NULL DEFAULT FALSE, client_updated_at BIGINT NOT NULL DEFAULT 0, server_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (user_id, session_id))`,
   sql`CREATE TABLE IF NOT EXISTS central_user_settings (user_id TEXT PRIMARY KEY REFERENCES central_sync_users(id) ON DELETE CASCADE, settings JSONB NOT NULL DEFAULT '{}'::jsonb, client_updated_at BIGINT NOT NULL DEFAULT 0, server_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
   sql`CREATE TABLE IF NOT EXISTS central_performance_sessions (user_id TEXT NOT NULL REFERENCES central_sync_users(id) ON DELETE CASCADE, session_id TEXT NOT NULL, storage_key TEXT NOT NULL, subject_id TEXT, module_id TEXT, topic_id TEXT, session_at TIMESTAMPTZ, minutes INTEGER NOT NULL DEFAULT 0, mastery TEXT, activities JSONB NOT NULL DEFAULT '[]'::jsonb, note TEXT, client_updated_at BIGINT NOT NULL DEFAULT 0, server_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (user_id, session_id))`,
   sql`CREATE INDEX IF NOT EXISTS idx_central_agenda_days_user_date ON central_agenda_days (user_id, agenda_date DESC)`,
   sql`CREATE INDEX IF NOT EXISTS idx_central_topic_progress_user_subject ON central_topic_progress (user_id, subject_id)`,
   sql`CREATE INDEX IF NOT EXISTS idx_central_anki_cards_user_updated ON central_anki_cards (user_id, client_updated_at DESC)`,
   sql`CREATE INDEX IF NOT EXISTS idx_central_decorando_items_user_updated ON central_decorando_items (user_id, client_updated_at DESC)`,
   sql`CREATE INDEX IF NOT EXISTS idx_central_decorando_attempts_user_item ON central_decorando_attempts (user_id, item_id, attempted_at)`,
   sql`CREATE INDEX IF NOT EXISTS idx_central_question_sessions_user_date ON central_question_sessions (user_id, session_date DESC)`,
   sql`CREATE INDEX IF NOT EXISTS idx_central_performance_sessions_user_date ON central_performance_sessions (user_id, session_at DESC)`
  ]);
 })().catch(e=>{schemaPromise=undefined;throw e})}
 return schemaPromise;
}

function normalizeAgendaRows(rows){if(!Array.isArray(rows))return[];return rows.slice(0,400).flatMap(row=>{const date=validDate(row?.date);if(!date)return[];const items=Array.isArray(row?.items)?safeJson(row.items.slice(0,100),[]):[];return[{date,items,updatedAt:cleanTimestamp(row?.updatedAt)}]})}
function normalizeProgressRows(rows){if(!Array.isArray(rows))return[];return rows.slice(0,500).flatMap(row=>{const topicKey=cleanString(row?.topicKey,220),subjectId=cleanString(row?.subjectId,64);if(!topicKey||!subjectId)return[];return[{topicKey,subjectId,topicId:cleanString(row?.topicId,160)||null,moduleId:cleanString(row?.moduleId,160)||null,theoryPct:cleanPct(row?.theoryPct),lawPct:cleanPct(row?.lawPct,true),ankiPct:cleanPct(row?.ankiPct),questionsPct:cleanPct(row?.questionsPct),overallPct:cleanPct(row?.overallPct),components:safeJson(row?.components&&typeof row.components==='object'?row.components:{},{}),updatedAt:cleanTimestamp(row?.updatedAt)}]})}
function normalizeAnkiCards(rows){if(!Array.isArray(rows))return[];return rows.slice(0,6000).flatMap(row=>{const cardId=cleanString(row?.cardId,220);if(!cardId)return[];const overrides=safeJson(row?.overrides&&typeof row.overrides==='object'?row.overrides:{},{},250_000);const custom=row?.customCard&&typeof row.customCard==='object'?safeJson(row.customCard,null,350_000):null;return[{cardId,stats:safeJson(row?.stats&&typeof row.stats==='object'?row.stats:{},{},80_000),suspended:bool(row?.suspended),overrides,customCard:custom,deleted:bool(row?.deleted),updatedAt:cleanTimestamp(row?.updatedAt)}]})}
function normalizeAnkiSettings(x){if(!x||typeof x!=='object')return null;const decks=Array.isArray(x.customDecks)?x.customDecks.slice(0,400).map(v=>cleanString(v,220)).filter(Boolean):[];return{customDecks:[...new Set(decks)],swapButtons:bool(x.swapButtons),updatedAt:cleanTimestamp(x.updatedAt)}}
function normalizeDecorandoItems(rows){if(!Array.isArray(rows))return[];return rows.slice(0,8000).flatMap(row=>{const itemId=cleanString(row?.itemId,220);if(!itemId)return[];return[{itemId,importance:['alta','media','baixa'].includes(row?.importance)?row.importance:null,note:cleanString(row?.note,12000)||null,highlights:safeJson(row?.highlights&&typeof row.highlights==='object'?row.highlights:{},{},80_000),answered:bool(row?.answered),deletedAt:cleanString(row?.deletedAt,60)||null,updatedAt:cleanTimestamp(row?.updatedAt)}]})}
function normalizeDecorandoAttempts(rows){if(!Array.isArray(rows))return[];return rows.slice(0,50000).flatMap(row=>{const attemptKey=cleanString(row?.attemptKey,260),itemId=cleanString(row?.itemId,220),date=validIso(row?.date);if(!attemptKey||!itemId||!date)return[];return[{attemptKey,itemId,date,choice:bool(row?.choice),correct:bool(row?.correct)}]})}
function normalizeDecorandoSettings(x){if(!x||typeof x!=='object')return null;return{preferences:safeJson(x.preferences&&typeof x.preferences==='object'?x.preferences:{},{},80_000),updatedAt:cleanTimestamp(x.updatedAt)}}


function normalizeQuestionSessions(rows){if(!Array.isArray(rows))return[];return rows.slice(0,5000).flatMap(row=>{const id=cleanString(row?.id,220);if(!id)return[];const deleted=bool(row?.deleted),quantity=Math.max(0,Math.min(100000,Math.trunc(Number(row?.questions)||0))),correct=Math.max(0,Math.min(quantity,Math.trunc(Number(row?.correct)||0))),minutes=row?.minutes==null||row?.minutes===''?null:Math.max(0,Math.min(100000,Math.trunc(Number(row.minutes)||0)));return[{id,subjectId:cleanString(row?.subjectId,64)||null,subject:cleanString(row?.subject,160)||null,topicId:cleanString(row?.topicId,180)||null,topicUid:cleanString(row?.topicUid,180)||null,moduleId:cleanString(row?.moduleId,180)||null,topic:cleanString(row?.topic,240)||null,date:validDate(row?.date)||null,questions:quantity,correct,minutes,difficulty:['facil','media','dificil'].includes(row?.difficulty)?row.difficulty:null,comment:cleanString(row?.comment,500)||null,deleted,updatedAt:cleanTimestamp(row?.updatedAt)}]})}
function normalizeUserSettings(x){if(!x||typeof x!=='object')return null;const appearance=['light','dark','system'].includes(x.appearance)?x.appearance:'dark',sidebar=['expanded','collapsed'].includes(x.sidebar)?x.sidebar:'expanded',g=Math.max(1,Math.min(1000,Math.round(Number(x.dailyQuestionGoal)||30)));return{settings:{appearance,sidebar,dailyQuestionGoal:g},updatedAt:cleanTimestamp(x.updatedAt)}}
function normalizePerformanceSessions(rows){if(!Array.isArray(rows))return[];const allowedKeys=new Set(['central-v7:sessions','central-v7:adm:sessions','central-v7:cpp:sessions']);return rows.slice(0,10000).flatMap(row=>{const id=cleanString(row?.id,260),storageKey=cleanString(row?.storageKey,80),date=validIso(row?.date);if(!id||!allowedKeys.has(storageKey)||!date)return[];return[{id,storageKey,subjectId:cleanString(row?.subjectId,64)||null,moduleId:cleanString(row?.moduleId,180)||null,topicId:cleanString(row?.topicId,180)||null,date,minutes:Math.max(0,Math.min(100000,Math.trunc(Number(row?.minutes)||0))),mastery:cleanString(row?.mastery,40)||null,activities:Array.isArray(row?.activities)?safeJson(row.activities.slice(0,20).map(v=>cleanString(v,60)).filter(Boolean),[]):[],note:cleanString(row?.note,1000)||null,updatedAt:cleanTimestamp(row?.updatedAt)}]})}
async function syncCentral(sql,userId,body){
 const agendaDays=normalizeAgendaRows(body.agendaDays);await runBatches(sql,agendaDays.map(row=>sql`INSERT INTO central_agenda_days (user_id,agenda_date,items,client_updated_at,server_updated_at) VALUES (${userId},${row.date},${JSON.stringify(row.items)}::jsonb,${row.updatedAt},NOW()) ON CONFLICT (user_id,agenda_date) DO UPDATE SET items=EXCLUDED.items,client_updated_at=EXCLUDED.client_updated_at,server_updated_at=NOW() WHERE EXCLUDED.client_updated_at>=central_agenda_days.client_updated_at`));
 const progress=normalizeProgressRows(body.progress);await runBatches(sql,progress.map(row=>sql`INSERT INTO central_topic_progress (user_id,topic_key,subject_id,topic_id,module_id,theory_pct,law_pct,anki_pct,questions_pct,overall_pct,components,client_updated_at,server_updated_at) VALUES (${userId},${row.topicKey},${row.subjectId},${row.topicId},${row.moduleId},${row.theoryPct},${row.lawPct},${row.ankiPct},${row.questionsPct},${row.overallPct},${JSON.stringify(row.components)}::jsonb,${row.updatedAt},NOW()) ON CONFLICT (user_id,topic_key) DO UPDATE SET subject_id=EXCLUDED.subject_id,topic_id=EXCLUDED.topic_id,module_id=EXCLUDED.module_id,theory_pct=EXCLUDED.theory_pct,law_pct=EXCLUDED.law_pct,anki_pct=EXCLUDED.anki_pct,questions_pct=EXCLUDED.questions_pct,overall_pct=EXCLUDED.overall_pct,components=EXCLUDED.components,client_updated_at=EXCLUDED.client_updated_at,server_updated_at=NOW() WHERE EXCLUDED.client_updated_at>=central_topic_progress.client_updated_at`));
 await runBatches(sql,normalizeQuestionSessions(body.questionSessions).map(row=>sql`INSERT INTO central_question_sessions (user_id,session_id,subject_id,subject_name,topic_id,topic_uid,module_id,topic_name,session_date,quantity,correct,minutes,difficulty,comment,deleted,client_updated_at,server_updated_at) VALUES (${userId},${row.id},${row.subjectId},${row.subject},${row.topicId},${row.topicUid},${row.moduleId},${row.topic},${row.date},${row.questions},${row.correct},${row.minutes},${row.difficulty},${row.comment},${row.deleted},${row.updatedAt},NOW()) ON CONFLICT (user_id,session_id) DO UPDATE SET subject_id=EXCLUDED.subject_id,subject_name=EXCLUDED.subject_name,topic_id=EXCLUDED.topic_id,topic_uid=EXCLUDED.topic_uid,module_id=EXCLUDED.module_id,topic_name=EXCLUDED.topic_name,session_date=EXCLUDED.session_date,quantity=EXCLUDED.quantity,correct=EXCLUDED.quantity*0+EXCLUDED.correct,minutes=EXCLUDED.minutes,difficulty=EXCLUDED.difficulty,comment=EXCLUDED.comment,deleted=EXCLUDED.deleted,client_updated_at=EXCLUDED.client_updated_at,server_updated_at=NOW() WHERE EXCLUDED.client_updated_at>=central_question_sessions.client_updated_at`));
 const settings=normalizeUserSettings(body.settings);if(settings)await sql`INSERT INTO central_user_settings (user_id,settings,client_updated_at,server_updated_at) VALUES (${userId},${JSON.stringify(settings.settings)}::jsonb,${settings.updatedAt},NOW()) ON CONFLICT (user_id) DO UPDATE SET settings=EXCLUDED.settings,client_updated_at=EXCLUDED.client_updated_at,server_updated_at=NOW() WHERE EXCLUDED.client_updated_at>central_user_settings.client_updated_at`;
 await runBatches(sql,normalizePerformanceSessions(body.performanceSessions).map(row=>sql`INSERT INTO central_performance_sessions (user_id,session_id,storage_key,subject_id,module_id,topic_id,session_at,minutes,mastery,activities,note,client_updated_at,server_updated_at) VALUES (${userId},${row.id},${row.storageKey},${row.subjectId},${row.moduleId},${row.topicId},${row.date},${row.minutes},${row.mastery},${JSON.stringify(row.activities)}::jsonb,${row.note},${row.updatedAt},NOW()) ON CONFLICT (user_id,session_id) DO UPDATE SET storage_key=EXCLUDED.storage_key,subject_id=EXCLUDED.subject_id,module_id=EXCLUDED.module_id,topic_id=EXCLUDED.topic_id,session_at=EXCLUDED.session_at,minutes=EXCLUDED.minutes,mastery=EXCLUDED.mastery,activities=EXCLUDED.activities,note=EXCLUDED.note,client_updated_at=EXCLUDED.client_updated_at,server_updated_at=NOW() WHERE EXCLUDED.client_updated_at>=central_performance_sessions.client_updated_at`));
 const agendaOut=await sql`SELECT agenda_date::text AS date,items,client_updated_at AS "updatedAt" FROM central_agenda_days WHERE user_id=${userId} ORDER BY agenda_date ASC`;
 const progressOut=await sql`SELECT topic_key AS "topicKey",subject_id AS "subjectId",topic_id AS "topicId",module_id AS "moduleId",theory_pct::float8 AS "theoryPct",law_pct::float8 AS "lawPct",anki_pct::float8 AS "ankiPct",questions_pct::float8 AS "questionsPct",overall_pct::float8 AS "overallPct",components,client_updated_at AS "updatedAt" FROM central_topic_progress WHERE user_id=${userId} ORDER BY subject_id,topic_key`;
 const questionSessions=await sql`SELECT session_id AS id,subject_id AS "subjectId",subject_name AS subject,topic_id AS "topicId",topic_uid AS "topicUid",module_id AS "moduleId",topic_name AS topic,session_date::text AS date,quantity AS questions,correct,minutes,difficulty,comment,deleted,client_updated_at AS "updatedAt" FROM central_question_sessions WHERE user_id=${userId} ORDER BY session_date ASC NULLS FIRST,session_id`;
 const setRows=await sql`SELECT settings,client_updated_at AS "updatedAt" FROM central_user_settings WHERE user_id=${userId}`;
 const performanceSessions=await sql`SELECT session_id AS id,storage_key AS "storageKey",subject_id AS "subjectId",module_id AS "moduleId",topic_id AS "topicId",session_at::text AS date,minutes,mastery,activities,note,client_updated_at AS "updatedAt" FROM central_performance_sessions WHERE user_id=${userId} ORDER BY session_at ASC NULLS FIRST,session_id`;
 return{agendaDays:agendaOut,progress:progressOut,questionSessions,settings:setRows[0]?{...(setRows[0].settings||{}),updatedAt:Number(setRows[0].updatedAt||0)}:null,performanceSessions};
}
async function syncAnki(sql,userId,body){
 const pack=body.anki&&typeof body.anki==='object'?body.anki:{};
 await runBatches(sql,normalizeAnkiCards(pack.cards).map(row=>sql`INSERT INTO central_anki_cards (user_id,card_id,stats,suspended,overrides,custom_card,deleted,client_updated_at,server_updated_at) VALUES (${userId},${row.cardId},${JSON.stringify(row.stats)}::jsonb,${row.suspended},${JSON.stringify(row.overrides)}::jsonb,${row.customCard?JSON.stringify(row.customCard):null}::jsonb,${row.deleted},${row.updatedAt},NOW()) ON CONFLICT (user_id,card_id) DO UPDATE SET stats=EXCLUDED.stats,suspended=EXCLUDED.suspended,overrides=EXCLUDED.overrides,custom_card=EXCLUDED.custom_card,deleted=EXCLUDED.deleted,client_updated_at=EXCLUDED.client_updated_at,server_updated_at=NOW() WHERE EXCLUDED.client_updated_at>=central_anki_cards.client_updated_at`));
 const settings=normalizeAnkiSettings(pack.settings);if(settings)await sql`INSERT INTO central_anki_settings (user_id,custom_decks,swap_buttons,client_updated_at,server_updated_at) VALUES (${userId},${JSON.stringify(settings.customDecks)}::jsonb,${settings.swapButtons},${settings.updatedAt},NOW()) ON CONFLICT (user_id) DO UPDATE SET custom_decks=EXCLUDED.custom_decks,swap_buttons=EXCLUDED.swap_buttons,client_updated_at=EXCLUDED.client_updated_at,server_updated_at=NOW() WHERE EXCLUDED.client_updated_at>=central_anki_settings.client_updated_at`;
 const cards=await sql`SELECT card_id AS "cardId",stats,suspended,overrides,custom_card AS "customCard",deleted,client_updated_at AS "updatedAt" FROM central_anki_cards WHERE user_id=${userId} ORDER BY card_id`;
 const setRows=await sql`SELECT custom_decks AS "customDecks",swap_buttons AS "swapButtons",client_updated_at AS "updatedAt" FROM central_anki_settings WHERE user_id=${userId}`;
 return{anki:{cards,settings:setRows[0]||null}};
}
async function syncDecorando(sql,userId,body){
 const pack=body.decorando&&typeof body.decorando==='object'?body.decorando:{};
 await runBatches(sql,normalizeDecorandoItems(pack.items).map(row=>sql`INSERT INTO central_decorando_items (user_id,item_id,importance,note,highlights,answered,deleted_at,client_updated_at,server_updated_at) VALUES (${userId},${row.itemId},${row.importance},${row.note},${JSON.stringify(row.highlights)}::jsonb,${row.answered},${row.deletedAt},${row.updatedAt},NOW()) ON CONFLICT (user_id,item_id) DO UPDATE SET importance=EXCLUDED.importance,note=EXCLUDED.note,highlights=EXCLUDED.highlights,answered=EXCLUDED.answered,deleted_at=EXCLUDED.deleted_at,client_updated_at=EXCLUDED.client_updated_at,server_updated_at=NOW() WHERE EXCLUDED.client_updated_at>=central_decorando_items.client_updated_at`));
 await runBatches(sql,normalizeDecorandoAttempts(pack.attempts).map(row=>sql`INSERT INTO central_decorando_attempts (user_id,attempt_key,item_id,attempted_at,choice,correct) VALUES (${userId},${row.attemptKey},${row.itemId},${row.date},${row.choice},${row.correct}) ON CONFLICT (user_id,attempt_key) DO NOTHING`));
 const settings=normalizeDecorandoSettings(pack.settings);if(settings)await sql`INSERT INTO central_decorando_settings (user_id,preferences,client_updated_at,server_updated_at) VALUES (${userId},${JSON.stringify(settings.preferences)}::jsonb,${settings.updatedAt},NOW()) ON CONFLICT (user_id) DO UPDATE SET preferences=EXCLUDED.preferences,client_updated_at=EXCLUDED.client_updated_at,server_updated_at=NOW() WHERE EXCLUDED.client_updated_at>=central_decorando_settings.client_updated_at`;
 const items=await sql`SELECT item_id AS "itemId",importance,note,highlights,answered,deleted_at AS "deletedAt",client_updated_at AS "updatedAt" FROM central_decorando_items WHERE user_id=${userId} ORDER BY item_id`;
 const attempts=await sql`SELECT attempt_key AS "attemptKey",item_id AS "itemId",attempted_at::text AS date,choice,correct FROM central_decorando_attempts WHERE user_id=${userId} ORDER BY attempted_at ASC`;
 const setRows=await sql`SELECT preferences,client_updated_at AS "updatedAt" FROM central_decorando_settings WHERE user_id=${userId}`;
 return{decorando:{items,attempts,settings:setRows[0]||null}};
}

export default async function handler(req,res){
 if(req.method!=='POST'){res.setHeader('Allow','POST');return res.status(405).json({ok:false,error:'Método não permitido'})}
 try{
  const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{}),syncKey=cleanString(body.syncKey,256);
  if(syncKey.length<12)return res.status(400).json({ok:false,error:'Código de sincronização inválido'});
  const sql=getSql();await ensureSchema(sql);const userId=userIdFor(syncKey);
  await sql`INSERT INTO central_sync_users (id,last_seen_at) VALUES (${userId},NOW()) ON CONFLICT (id) DO UPDATE SET last_seen_at=NOW()`;
  const scope=cleanString(body.scope||'central',24).toLowerCase();let out={ok:true};
  if(scope==='anki')Object.assign(out,await syncAnki(sql,userId,body));
  else if(scope==='decorando')Object.assign(out,await syncDecorando(sql,userId,body));
  else Object.assign(out,await syncCentral(sql,userId,body));
  res.setHeader('Cache-Control','no-store');return res.status(200).json(out);
 }catch(error){console.error('Central V23 sync error',error);return res.status(500).json({ok:false,error:'Falha na sincronização online'})}
}
